### PR TITLE
Issue 647: Fixed v2 PageImpl not being able to export content

### LINKED ISSUE #647: [Page] Content Exporter Not Working - Throwing UnsupportedOperationException
## Bug Report

**Current Behavior**
In my proxy model, when I attempt to get a content export of a page, the Servlet handling `.model.json` is erroring out due to an UnsupportedOperationException being thrown.

**Expected behavior/code**
A user can successfully request a content export of a page utilizing a proxy model or the WCM Core model by adding `.model.json` to the page path without any errors.

**Environment**
- AEM version and patch level AEM 6.3.3.2 + AEM 6.4.2
- Core Components version 2.4.0
- JRE version Java(TM) SE Runtime Environment (build 1.8.0_152-b16)

**Possible Solution**
~~The getFavicons() method on the v2 PageImpl should not throw an UnsupportedOperationException when called.~~
The content exporter should omit the getFavicons() method.

**Additional context / Screenshots**
In order for me to get the content export to function correctly, I had to override the getFavicons() method in my proxy model to bypass the WCM Core functionality causing the content export to not work since that getter throws an UnsupportedOperationException. My proposed fix is to ~~just rely on v1 PageImpl's getFavicons() method since the method is already deprecated in the interface~~ use the JsonIgnore annotation on this method.

### PR DESCRIPTION
**Pull request by brandonmaynard**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #647 
| Patch: Bug Fix?          | Bug Fix
| Minor: New Feature?      | No
| Major: Breaking Change?  | No
| Tests Added + Pass?      | Yes
| Documentation Provided   | Yes (code comments and or markdown)
| Any Dependency Changes?  | No
| License                  | Apache License, Version 2.0

### CODE REVIEW

File: bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v2/PageImplTest.java [hunk 1]
```diff
@@ -83,11 +84,11 @@ public void testPage() throws ParseException {
         testJSONExport(page, getTestExporterJSONPath(TEST_BASE, PAGE));
     }
 
-    @Test(expected = UnsupportedOperationException.class)
+    @Test
     @Override
     public void testFavicons() {
         Page page = getPageUnderTest(PAGE);
-        page.getFavicons();
+        assertEquals(new HashMap<>(), page.getFavicons());
```
Comment (brandonmaynard) [inline bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v2/PageImplTest.java]: I am not sure how we should test this method since it went from throwing an exception, to now using v1 functionality. The empty HashMap is being used here just to not break the build. Should I add paths for favicons to the v2 content JSON (like what is being done for v1) or something different?
