### PR TITLE
DataLayer AssetData backward compatibility #1415

### LINKED ISSUE #1415: DataLayer AssetData backward compatibility
## Bug Report

**Current Behavior**
In Core CIF Components, we implemented the `dataLayer` functionality on top of Core WCM.
CIF Components relies on version `2.9.0` of Core WCM Components.

Lately, we extended some the `dataLayer` for some components to include asset data. And for that we [implemented](https://github.com/adobe/aem-core-cif-components/blob/core-cif-components-reactor-1.8.0/bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/datalayer/AssetDataImpl.java) the `AssetData` interface

The problem is that when more recent version on Core WCM Components bundles are present (2.15.0 for example), the serialization of the `dataLayer` for those models fails. Version 2.15.0 is included in the latest AEMaaCS build.

The culprit is the new `getSmartTags` method of `AssetData` that has a `default` behavior of throwing `UnsupportedOperationException`.

**Expected behavior/code**
Default implementation of new methods added on interfaces should not break existing functionality.

**Environment**
- AEM SDK v2021.2.4944.20210221T230729Z-210128
- Core Components version 2.15.0
- JDK11

**Possible Solution**

**Additional context / Screenshots**
```
26.02.2021 13:34:28.564 *ERROR* [[0:0:0:0:0:0:0:1] [1614339266359] GET /content/venia/us/en/products/product-page.honora-wide-leg-pants.html HTTP/1.1] com.adobe.cq.commerce.core.components.internal.datalayer.ComponentDataImpl Unable to generate dataLayer JSON string
com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.UnsupportedOperationException) (through reference chain: com.adobe.cq.commerce.core.components.internal.datalayer.ProductDataImpl["xdm:assets"]->com.adobe.cq.commerce.core.components.internal.datalayer.AssetDataImpl[0]->com.adobe.cq.commerce.core.components.internal.datalayer.AssetDataImpl["xdm:smartTags"])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:397) [com.fasterxml.jackson.core.jackson-databind:2.11.3
```

### PR DESCRIPTION
**Pull request by vladbailescu**
* Switched all default methods to no longer throw UnsupportedOperationException
* Removed default methods that could be inherited from super-interfaces
* Methods will return null where the return type is not primitive or annotated as NotNull
* Updated tests
* Cleaned up imports

Fixes #1415

### CODE REVIEW

**Review by bpauli — COMMENTED** [review]
@vladbailescu Maybe we should trace a message in case we return a default value by the default method? Something like `log.trace("return default value " + value)` Customers can than easily  detect new methods in the interface which they might want to implement in their own Sling Model.

**Comment by cjelger** [comment]
@bpauli I'm wondering if this useful at all: I think usually customers would find out about new methods because they have a need to use them, they are probably not interested in anything they don't need for a good reason. Also the default Sling model implementation would usually implement all methods, so this is only useful for `default` methods that are not going to be implemented in the WCM component models.

**Comment by bpauli** [comment]
@cjelger In some cases the default methods might be used by FE devs which might not be aware that there is no meaningful implementation. As the suggested message would only be logged when the method is used it might be a useful way to get some insights.

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Component.java [hunk 1]
```diff
@@ -72,6 +72,6 @@ default ComponentData getData() {
     @NotNull
     @Override
     default String getExportedType() {
```
Comment (msagolj) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Component.java:74]: can't this method not also be removed because its an override ?

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Accordion.java [hunk 2]
```diff
@@ -50,7 +50,7 @@ default boolean isSingleExpansion() {
      * @since com.adobe.cq.wcm.core.components.models 12.8.0
      */
     default String[] getExpandedItems() {
-        throw new UnsupportedOperationException();
+        return null;
```
Comment (msagolj) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Accordion.java:53]: Shouldn't all the default methods that now return `null` instead of an exception have a `@Nullable` Annotation to mark the method as potentially returning a `null` value ?

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Component.java (hunk 1 above)
Comment (vladbailescu) [reply bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Component.java:74]: It overrides the method in `ComponentExporter` which does not provide a `default`.

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Accordion.java (hunk 2 above)
Comment (vladbailescu) [reply bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Accordion.java:53]: I believe most static analysis tools will treat no annotation as `@Nullable` for method return types. I see no point in being explicit here. The contract is more important for `@NotNull`.

Comment (msagolj) [reply bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Accordion.java:53]: ok

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/LanguageNavigation.java [hunk 3]
```diff
@@ -51,16 +47,7 @@
      * @since com.adobe.cq.wcm.core.components.models 12.2.0
      */
     default List<NavigationItem> getItems() {
-        throw new UnsupportedOperationException();
+        return null;
```
Comment (jckautzmann) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/LanguageNavigation.java:50]: Shouldn't we return an empty list as a general pattern (as done above)?

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/List.java [hunk 4]
```diff
@@ -149,7 +149,7 @@
      */
     @Deprecated
     default Collection<Page> getItems() {
-        throw new UnsupportedOperationException();
+        return null;
```
Comment (jckautzmann) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/List.java:152]: shouldn't we return an empty list (see comment above)?

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Navigation.java [hunk 5]
```diff
@@ -79,17 +75,7 @@
...
-
-    /**
-     * @see ComponentExporter#getExportedType()
-     * @since com.adobe.cq.wcm.core.components.models 12.2.0
-     */
-    @NotNull
-    @Override
-    default String getExportedType() {
-        throw new UnsupportedOperationException();
+        return null;
```
Comment (jckautzmann) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Navigation.java:78]: shouldn't we return an empty list (see comment above)?

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/NavigationItem.java [hunk 6]
```diff
@@ -60,7 +60,7 @@ default boolean isActive() {
      * @since com.adobe.cq.wcm.core.components.models 12.2.0
      */
     default List<NavigationItem> getChildren() {
-        throw new UnsupportedOperationException();
+        return null;
```
Comment (jckautzmann) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/NavigationItem.java:63]: shouldn't we return an empty list (see comment above)?

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Page.java [hunk 7]
```diff
@@ -168,7 +169,7 @@ default Calendar getLastModifiedDate() {
      */
     @JsonIgnore
     default String[] getKeywords() {
-        throw new UnsupportedOperationException();
+        return null;
```
Comment (jckautzmann) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Page.java:172]: shouldn't we return an empty array (see comment above)?

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Page.java [hunk 8]
```diff
@@ -248,7 +249,7 @@ default String getBrandSlug() {
      */
     @JsonIgnore
     default String[] getClientLibCategories() {
-        throw new UnsupportedOperationException();
+        return null;
```
Comment (jckautzmann) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Page.java:252]: shouldn't we return an empty list (see comment above)?

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Page.java [hunk 9]
```diff
@@ -261,7 +262,7 @@ default String getBrandSlug() {
      */
     @JsonIgnore
     default String[] getClientLibCategoriesJsBody() {
-        throw new UnsupportedOperationException();
+        return null;
```
Comment (jckautzmann) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Page.java:265]: shouldn't we return an empty list (see comment above)?

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Page.java [hunk 10]
```diff
@@ -274,7 +275,7 @@ default String getBrandSlug() {
      */
     @JsonIgnore
     default String[] getClientLibCategoriesJsHead() {
-        throw new UnsupportedOperationException();
+        return null;
```
Comment (jckautzmann) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Page.java:278]: shouldn't we return an empty list (see comment above)?

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/SocialMediaHelper.java [hunk 11]
```diff
@@ -138,16 +135,7 @@ default boolean hasPinterestSharing() {
      * @since com.adobe.cq.wcm.core.components.models 11.0.0; marked <code>default</code> in 12.1.0
      */
     default Map<String, String> getMetadata() {
-        throw new UnsupportedOperationException();
+        return null;
```
Comment (jckautzmann) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/SocialMediaHelper.java:138]: shouldn't we return an empty map (see comment above)?

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Teaser.java [hunk 12]
```diff
@@ -143,7 +142,7 @@ default boolean isActionsEnabled() {
      * @since com.adobe.cq.wcm.core.components.models 12.4.0
      */
     default List<ListItem> getActions() {
-        throw new UnsupportedOperationException();
+        return null;
```
Comment (jckautzmann) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Teaser.java:145]: shouldn't we return an empty list (see comment above)?

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/contentfragment/DAMContentFragment.java [hunk 13]
```diff
@@ -249,7 +250,7 @@ default String getType() {
     @Nullable
     @JsonIgnore
     default List<DAMContentElement> getElements() {
-        throw new UnsupportedOperationException();
+        return null;
```
Comment (jckautzmann) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/contentfragment/DAMContentFragment.java:253]: shouldn't we return an empty list (see comment above)?

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/contentfragment/DAMContentFragment.java [hunk 14]
```diff
@@ -290,7 +291,7 @@ default String getType() {
     @Nullable
     @JsonIgnore
     default List<Resource> getAssociatedContent() {
-        throw new UnsupportedOperationException();
+        return null;
```
Comment (jckautzmann) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/contentfragment/DAMContentFragment.java:294]: shouldn't we return an empty list (see comment above)?

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/datalayer/AssetData.java [hunk 15]
```diff
@@ -75,7 +75,7 @@ default String getFormat() {
      */
     @JsonProperty("xdm:tags")
     default String[] getTags() {
-        throw new UnsupportedOperationException();
+        return null;
```
Comment (jckautzmann) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/datalayer/AssetData.java:78]: shouldn't we return an empty array (see comment above)?

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/datalayer/AssetData.java [hunk 16]
```diff
@@ -100,7 +100,7 @@ default Date getLastModifiedDate() {
      */
     @JsonProperty("xdm:smartTags")
     default Map<String, Object> getSmartTags() {
-        throw new UnsupportedOperationException();
+        return null;
```
Comment (jckautzmann) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/datalayer/AssetData.java:103]: shouldn't we return an empty list (see comment above)?

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/datalayer/ContainerData.java [hunk 17]
```diff
@@ -30,6 +30,6 @@
      * @since com.adobe.cq.wcm.core.components.models.datalayer 1.0.0
      */
     default String[] getShownItems() {
-        throw new UnsupportedOperationException();
+        return null;
```
Comment (jckautzmann) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/datalayer/ContainerData.java:33]: shouldn't we return an empty array (see comment above)?

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/datalayer/ContentFragmentData.java [hunk 18]
```diff
@@ -28,7 +28,7 @@
      */
     @JsonProperty("elements")
     default ElementData[] getElementsData() {
-        throw new UnsupportedOperationException();
+        return null;
```
Comment (jckautzmann) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/datalayer/ContentFragmentData.java:31]: shouldn't we return an empty array (see comment above)?

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/datalayer/PageData.java [hunk 19]
```diff
@@ -33,7 +33,7 @@
      */
     @JsonProperty("xdm:tags")
     default String[] getTags() {
-        throw new UnsupportedOperationException();
+        return null;
```
Comment (jckautzmann) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/datalayer/PageData.java:36]: shouldn't we return an empty array (see comment above)?

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/LanguageNavigation.java (hunk 3 above)
Comment (vladbailescu) [reply bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/LanguageNavigation.java:50]: I opted to return `null` for all methods (expect primitives and those annotated with `@NotNull`) as these properties will then be omitted during JSON serialization and I find that nicer than: `items:[]`

**Review by bpauli — APPROVED** [review]

**Review by jckautzmann — APPROVED** [review]
