### PR TITLE
initial commit of result limit for Content fragment list component

### LINKED ISSUE #598: [Content Fragment List] Max display of 10?
## Bug Report

**Current Behavior**
When experimenting with the Content Fragment List component I cannot configure the filters to return more than 10 fragments (even though more than 10 exist).

**Expected behavior/code**
I would expect the component to return all content fragment fragments based on the configured filters. Ideally, a user has a way to configure the max amount of items as either a policy or dialog configuration.

**Environment**
- AEM 6.5
- Core Components version 2.4.0
- JRE version 1.8

**Possible Solution**

Update https://github.com/adobe/aem-core-wcm-components/blob/development/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentListImpl.java#L120 to include an explicit `p.limit` parameter that is configured at the component's policy/component level...

Otherwise, I think the QueryBuilder API defaults to a limit of 10...

### PR DESCRIPTION
**Pull request by godanny86**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #598 
| Patch: Bug Fix?          | Could be interpreted as an enhancement or bugfix (depending on perspective)
| Minor: New Feature?      | Yes
| Major: Breaking Change?  |
| Tests Added + Pass?      | No, initial PR to gather feedback
| Documentation Provided   | No, initial PR to gather feedback
| Any Dependency Changes?  | Yes incremented `com.adobe.cq.wcm.core.components.models.contentfragment` from 1.0.0 to 1.1.0
| License                  | Apache License, Version 2.0

Currently, the CF List component appears to return a max number of 10 fragments, see issue #598. This PR adds a Result Limit to the Content Fragment List dialog. 

This allows a content author to:

* configure the max amount of fragments to display in the component or
* add a value of **-1** to include all content fragments (that are returned by the filter)

image

The `resultLimit` property value is translated to the `p.limit` value of the querybuilder parameters. Continues to use a default of 10 results (as before) if no `resultLimit` property is set but this time explicitly sets the `p.limit`.

### CODE REVIEW

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentListImpl.java [hunk 1]
```diff
@@ -91,6 +94,10 @@
     @ValueMapValue(name = ContentFragmentList.PN_PARENT_PATH, injectionStrategy = InjectionStrategy.OPTIONAL)
     private String parentPath;
 
+    @ValueMapValue(name = ContentFragmentList.PN_RESULT_LIMIT, injectionStrategy = InjectionStrategy.OPTIONAL)
+    @Default(intValues = DEFAULT_RESULT_LIMIT)
+    private int resultLimit;
```
Comment (jckautzmann) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentListImpl.java]: I would call the property `maxItems` to be consistent with the Core List component.

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/contentfragment/ContentFragmentList.java [hunk 2]
```diff
@@ -67,6 +67,13 @@
      */
     String PN_PARENT_PATH = "parentPath";
 
+    /**
+     * Name of the optional resource property that sets the query limit for the number of results to return.
+     *
+     * @since com.adobe.cq.wcm.core.components.models.contentfragment 1.1.0
+     */
+    String PN_RESULT_LIMIT = "resultLimit";
```
Comment (jckautzmann) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/contentfragment/ContentFragmentList.java]: See name suggestion above.

File: content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/_cq_dialog/.content.xml [hunk 3]
```diff
@@ -92,6 +92,27 @@
                             </column>
                         </items>
                     </elements>
+                    <results
```
Comment (jckautzmann) [inline content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/_cq_dialog/.content.xml]: I would add the configuration to the `Properties` tab. Having a new tab with only one property looks weird.

File: content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/_cq_dialog/.content.xml [hunk 4]
```diff
@@ -92,6 +92,27 @@
...
+                                jcr:primaryType="nt:unstructured"
+                                sling:resourceType="granite/ui/components/coral/foundation/container">
+                                <items jcr:primaryType="nt:unstructured">
+                                    <resultLimit
+                                        jcr:primaryType="nt:unstructured"
+                                        sling:resourceType="granite/ui/components/coral/foundation/form/numberfield"
+                                        fieldDescription="Maximum number of fragments displayed, defaults to 10. Enter -1 for all items"
+                                        fieldLabel="Result Limit"
+                                        min="{Long}-1"
+                                        name="./resultLimit"/>
```
Comment (jckautzmann) [inline content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/_cq_dialog/.content.xml]: See name suggestion above.

File: content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/_cq_dialog/.content.xml [hunk 5]
```diff
@@ -92,6 +92,27 @@
...
+                        <items jcr:primaryType="nt:unstructured">
+                            <column
+                                jcr:primaryType="nt:unstructured"
+                                sling:resourceType="granite/ui/components/coral/foundation/container">
+                                <items jcr:primaryType="nt:unstructured">
+                                    <resultLimit
+                                        jcr:primaryType="nt:unstructured"
+                                        sling:resourceType="granite/ui/components/coral/foundation/form/numberfield"
+                                        fieldDescription="Maximum number of fragments displayed, defaults to 10. Enter -1 for all items"
+                                        fieldLabel="Result Limit"
```
Comment (jckautzmann) [inline content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/_cq_dialog/.content.xml]: I would rename it `Max Items` (same as for the Core List component).

**Comment by jckautzmann** [comment]
Thx @godanny86 for spotting this issue and providing a pull request. It seems that the QueryBuilder json servlet displays a maximum of 10 hits. Your PR fixes this issue. I added some remarks in the PR (mostly about the configuration name). Some more comment:
- Could you please update the component README.md with the new configuration?
- Could you also add a test?

**Comment by godanny86** [comment]
Sure think @jckautzmann, couple of questions:

To be more consistent with the List component should I update the logic of the dialog/model to be "Maximum number of items displayed in the list. Empty for all items." Or stick with what I currently have?
image

I will also add a unit test. Interestingly, I was surprised that [verifyQueryBuilderInteractionWhenPathParameterAndTagsAreGiven](https://github.com/adobe/aem-core-wcm-components/blob/development/bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentListImplTest.java#L169) and [verifyQueryBuilderInteractionWhenNonExistingModelIsGiven](https://github.com/adobe/aem-core-wcm-components/blob/development/bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentListImplTest.java#L141) continued to pass even with my additional codes (since I'm always updating the query parameters). Will investigate further...

**Comment by richardhand** [comment]
@godanny86 

>To be more consistent with the List component should I update the logic of the dialog/model to be "Maximum number of items displayed in the list. Empty for all items." Or stick with what I currently have?

+1 for empty to show all items like we have in the list component.

File: content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/_cq_dialog/.content.xml (hunk 3 above)
Comment (richardhand) [reply content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/_cq_dialog/.content.xml]: Probably makes best sense below the current `Tags` field (below filters, as in the List component)

File: content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/_cq_dialog/.content.xml [hunk 6]
```diff
@@ -53,6 +53,14 @@
                                         fieldLabel="Tags"
                                         multiple="{Boolean}true"
                                         name="./tagNames"/>
+                                    <maxItems
+                                        jcr:primaryType="nt:unstructured"
+                                        sling:resourceType="granite/ui/components/coral/foundation/form/numberfield"
+                                        fieldDescription="Maximum number of items displayed in list. Empty for all items."
+                                        fieldLabel="Max Items"
+                                        min="{Long}0"
+                                        value="{Long}10"
```
Comment (jckautzmann) [inline content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/_cq_dialog/.content.xml]: I would not set the default limit to 10, the default should be empty (all items).

Comment (richardhand) [reply content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/_cq_dialog/.content.xml]: If we do this I would be +1 to merge.

**Comment by jckautzmann** [comment]
Thx for your work @godanny86 ! I merged your pull request.

File: content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/_cq_dialog/.content.xml (hunk 6 above)
Comment (jckautzmann) [reply content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/_cq_dialog/.content.xml]: I went ahead and added this change directly to the `development` branch:
https://github.com/adobe/aem-core-wcm-components/commit/003391ea93f9044302d98b8fb2de64b47b002a31

**Comment by godanny86** [comment]
great thank you @jckautzmann!
