### PR TITLE
[Teaser][Download] - the description area of the dialog is not editab…

### LINKED ISSUE #1295: [Teaser][Download] - the description area of the dialog is not editable on a Cloud instance
## Bug Report

**Current Behavior**
When opening the dialog of the Teaser and the Download components, the description area remains greyed out on various cloud environments.

This issue does not happen on local instances.

### PR DESCRIPTION
**Pull request by jckautzmann**
…le on a Cloud instance

- instantiate the fields only when both the dialog and the description RTE have loaded

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #1295 
| Patch: Bug Fix?          |
| Minor: New Feature?      |
| Major: Breaking Change?  |
| Tests Added + Pass?      | No
| Documentation Provided   | No
| Any Dependency Changes?  |
| License                  | Apache License, Version 2.0

### CODE REVIEW

**Comment by bartoszglow** [comment]
Does the provided solution assume that description textfield will not be initialized in case RTE was slow unless you start to edit it?

File: content/src/content/jcr_root/apps/core/wcm/components/download/v1/download/clientlibs/editor/js/download.js [hunk 1]
```diff
@@ -35,37 +35,51 @@
...
-                    titleTuple.reset();
-                    descriptionTuple.reset();
+
+            var rteInstance = $(descriptionTextfieldSelector).data("rteinstance");
+            // wait for the description textfield rich text editor to signal start before initializing.
+            if (rteInstance && rteInstance.isActive) {
+                init($dialog, dialogContent);
+            } else {
+                $(descriptionTextfieldSelector).on("editing-start", function() {
+                    init($dialog, dialogContent);
```
Comment (vladbailescu) [inline content/src/content/jcr_root/apps/core/wcm/components/download/v1/download/clientlibs/editor/js/download.js:45]: Won't this lead to multiple initialisations? If so, we should keep track if the initialisation already happened to avoid doing it multiple times.

Comment (jckautzmann) [reply content/src/content/jcr_root/apps/core/wcm/components/download/v1/download/clientlibs/editor/js/download.js:45]: I tested it on localhost and cloud and can confirm that it only initializes once.

**Comment by jckautzmann** [comment]
> Does the provided solution assume that description textfield will not be initialized in case RTE was slow unless you start to edit it?

@bartoszglow no, the fix makes sure that the fields are initialized once both the dialog and the description textfield RTE have loaded. the `editing-start` event is triggered when the RTE is ready, when editing can start.

**Review by bartoszglow — APPROVED** [review]

**Review by vladbailescu — APPROVED** [review]
