### PR TITLE
[Title] Default heading size option is not reflected in dialog

### LINKED ISSUE #629: [Title] Default heading size option is not reflected in dialog
## Bug Report

**Current Behavior**
Configuration of default heading size on policy of title component is not reflected on dialog of newly added Title component on a page using this policy.

Title component right after being added correctly uses the default heading size, but once the dialog is opened, the heading size option in this dialog is not the same as the default option, which causes the component to use different heading tag once the dialog is saved.

Reproduction steps:
* Open Title component demo page
* Go to template of the page
* Open policy of Title v2 component
* Change default heading size option to e.g. h5
* Go back to the Title component demo page
* Add new Title v2 component (component uses correct tag)
* Open dialog (different value for heading size is set than the default one set in policy)

**Expected behavior/code**
Default heading size configuration from policy is reflected in heading size option in dialog of newly added component.

**Environment**
- Core Components version 2.4.0

** More info **
This issue seems like something that could happen in more then one component and I think that the solution for this could be reused for other (even new and custom) components. Would you consider any more generic solution? 

Maybe some JS logic added on authoring level which would react once a dialog is opened and which looks for some specific attribute on dialog elements?

### PR DESCRIPTION
**Pull request by bpauli**
- extend TextValueDataResourceSource with selected property
- add default type to data source servlet for allowed headings
fixes #629

### CODE REVIEW

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AllowedHeadingElementsDataSourceServlet.java [hunk 1]
```diff
@@ -52,6 +52,7 @@
     public final static String RESOURCE_TYPE_TITLE_V1 = "core/wcm/components/title/v1/datasource/allowedtypes";
     public final static String PN_ALLOWED_HEADING_ELEMENTS = "allowedHeadingElements";
     public final static String PN_ALLOWED_TYPES = "allowedTypes";
+    public final static String PN_DEFAULT_TYPE = "type";
```
Comment (richardhand) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AllowedHeadingElementsDataSourceServlet.java]: @pauli, we should add `PN_DEFAULT_HEADING_ELEMENT = "headingElement";` and test this also works in the accordion component.
