### PR TITLE
[Image] The image of the image component placed in the accordion of the template editor is not displayed.

### LINKED ISSUE #907: [Image] The image of the image component placed in the accordion of the template editor is not displayed.
## Bug Report

**Current Behavior**
This problem only occurs in the template editor.

Steps (See attached video):

1. Place the Accordion component.
2. Select the image component for item 1.
3. Sets an image to an image component.

Behavior:
The image set in the image component is not displayed.

**Expected behavior/code**
The image set in the image component is displayed.

**Environment**
- AEM version and patch level: 6.5.0.0
- Core Components version:2.5.0
- JRE version: Java(TM) SE Runtime Environment 18.9 (build 11.0.5+10-LTS)

**Possible Solution**

**Additional context / Screenshots**
Video:[Content Page.mp4.zip](https://github.com/adobe/aem-core-wcm-components/files/4184373/Content.Page.mp4.zip)
errorlog:[errorlog.zip](https://github.com/adobe/aem-core-wcm-components/files/4184291/errorlog.zip)

### PR DESCRIPTION
**Pull request by richardhand**
- when timestamp matching image suffixes, also check for a preceding forward slash to help prevent false matches.

The problem reported in #907 is related to all container components (accordion, tabs, carousel) where paths for items that are added via the dialog also contain a postfixed 13 digit timestamp in their path. In the adaptive image servlet the timestamp was matched based only on a 13 digit number, which resulted in an out of bounds exception in this case when determining a substring. This pull request makes the matching a little more robust by also expecting a preceding forward slash.

#### Example, with wrongly matched timestamp emboldened:

/conf/core-components-examples/settings/wcm/templates/content-page/structure.coreimg.jpeg/structure/_jcr_content/root/responsivegrid/accordion/item__**1581514061965**/1581514094392/mountain-range.jpeg

__

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | `Fixes #907` 
| Patch: Bug Fix?          | 👍
| Minor: New Feature?      |
| Major: Breaking Change?  |
| Tests Added + Pass?      |
| Documentation Provided   |
| Any Dependency Changes?  |
| License                  | Apache License, Version 2.0

### CODE REVIEW

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java [hunk 1]
```diff
@@ -736,8 +736,8 @@ private Integer getAllowedJpegQuality(@NotNull Resource imageResource) {
     private long getRequestLastModifiedSuffix(@Nullable String suffix) {
         long requestLastModified = 0;
         if (StringUtils.isNotEmpty(suffix) && suffix.contains(".")) {
-            // check if the 13 digits UTC milliseconds timestamp is present in the suffix
-            Pattern p = Pattern.compile("\\(|\\)|\\d{13}");
+            // check if the 13 digits UTC milliseconds timestamp, proceeded by a forward slash is present in the suffix
+            Pattern p = Pattern.compile("\\(|\\)|\\/\\d{13}");
```
Comment (jckautzmann) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java]: typo? Shouldn't it be proceeded -> preceded?

Comment (richardhand) [reply bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java]: revolved in 218fac0354c2d75031880b3ac0888455f621c9e4
