### PR TITLE
Fix Design Dialog for custom embeddable

### LINKED ISSUE #1481: [Embeddable] Design Dialog for the custom embeddable not working as expected
## Bug Report

[custom-embed-1.0.zip](https://github.com/adobe/aem-core-wcm-components/files/6237134/custom-embed-1.0.zip)

Embed-Policy

**Current Behavior**
 Created an additional embeddable for Vimeo(copied YouTube embeddable and modified the required properties)
 - The design dialog tab for the additional embeddable(Vimeo) is always displayed
 - The design dialog tab for the YouTube is not visible while the additional embeddable is selected(Vimeo)

**Expected behavior/code**
The design dialog tab should be displayed based on the embeddable selection
 - YouTube tab should be displayed on selection of YouTube
 - Additional tabs should be displayed based on the custom embeddable(Vimeo) selection
 - Multiple tabs displayed on selecting multiple embeddable

**Environment**
- AEM version and patch level - aem-sdk-quickstart-2021.2.4887.20210204T154817Z-210128
- Core Components version -  2.15.2
- JRE version (e.g. `Java(TM) SE Runtime Environment (build 1.8.0_152-b16)`) - "11.0.9"

**Possible Solution**

**Additional context / Screenshots**
Attaching the package with custom embeddable(Vimeo) along with the screenshot

### PR DESCRIPTION
**Pull request by bpauli**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #1481 
| Patch: Bug Fix?          |
| Minor: New Feature?      |
| Major: Breaking Change?  |
| Tests Added + Pass?      | Yes
| Documentation Provided   | Yes (code comments and or markdown)
| Any Dependency Changes?  |
| License                  | Apache License, Version 2.0

### CODE REVIEW

File: content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed/clientlibs/editor/js/embed.js [hunk 1]
```diff
@@ -238,17 +237,14 @@
...
-    function toggleShowHideTabs(panelSelectors, value) {
-        var panelElements = document.querySelectorAll(panelSelectors);
-
-        for (var i = 0; i < panelElements.length; i++) {
-            var panelElement = panelElements[i];
-            var showHideTargetValue = getShowHideTargetValue(panelElement);
-            var tabElement = getTabElementForPanel(panelElement);
-            if (showHideTargetValue === value) {
+    function toggleShowHideTabs(values) {
+        var panelElement = document.querySelectorAll("[data-cmp-embed-dialog-edit-embeddableoptions]");
```
Comment (jckautzmann) [inline content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed/clientlibs/editor/js/embed.js:243]: I'd name it `panelElements` (plural) as it can contain several elements.

Comment (bpauli) [reply content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed/clientlibs/editor/js/embed.js]: changed in 1d10a84c2ff4c13074767a5a7aea58f71deac6cf

**Review by jckautzmann — APPROVED** [review]
