### PR TITLE
Ensure service resource resolvers are closed

### LINKED ISSUE #1118: Unclosed resource resolver in `Utils.getComponentsResolver`
## Bug Report

**Current Behavior**
The utility method `Utils.getComponentsResolver()` returns a new resource resolver for the `components-service` sub-service.
These resource resolvers are never closed.

**Expected behavior/code**
The resource resolvers should be closed.

**Environment**
- AEM 6.5.5.0
- Core Components 2.11.0
- JDK 11

**Possible Solution**
The resource resolvers should be closed once we are done with them.
This can be tricky to accomplish when the calling method may simply have access to a resource resolved using that resource resolver, which may be null - leaving no method of closing the resource resolver.

Preferably the utility methods that create a new resource resolver should simply be removed and the actual implementations that are requiring service-user based resource resolvers should be responsible for their creation. A simple solution is then to wrap the entire section in a try-with-resources block to ensure that the resource resolvers are always closed. 

Essentially, i would find every method that has a parameter of type `ResourceResolverFactory` and simply replace that with `ResourceResolver` instead. The caller that invokes the method is then responsible for supplying a resource resolver with the required permissions based on the sub-service requirements.

### PR DESCRIPTION
**Pull request by ky940819**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #1118 
| Patch: Bug Fix?          | yes
| Minor: New Feature?      | no
| Major: Breaking Change?  | no
| Tests Added + Pass?      | none added
| Documentation Provided   | Yes (code comments)
| Any Dependency Changes?  | no
| License                  | Apache License, Version 2.0

@vladbailescu Sorry I already had this staged when i saw you pushed #1120. I should have clarified that I would suggest a solution. I'll offer it up anyway if there is any interest in it.
 
- Removes utility for creating service resource resolvers with elevated permissions; requires caller to provide resource resolver
- Uses try-with-resource from caller (`ComponentFilesImpl` & `ClientLibrariesImpl`) to ensure that the resource resolver is closed, this also opens the potential to use different service users for different tasks in the future.
- Fixes a theoretical NPE in `Utils` due to page content resource potentially being null
- Reworks `ClientLibrariesImpl` a bit to have less deep nesting of conditions/loops (no functional change)

### CODE REVIEW

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/Utils.java [hunk 1]
```diff
@@ -211,82 +206,30 @@ public static String generateId(String prefix, String path) {
...
-    private static void addSuperTypes(@NotNull String resourceType, @NotNull Set<String> superTypes, @NotNull SlingHttpServletRequest request, ResourceResolverFactory resolverFactory) {
-        Resource resource = getResource(resourceType, request, resolverFactory);
-        if (resource != null) {
-            String superType = resource.getResourceSuperType();
-            if (StringUtils.isNotEmpty(superType) && !superTypes.contains(superType)) {
-                superTypes.add(superType);
-                addSuperTypes(superType, superTypes, request, resolverFactory);
-            }
-        }
+    public static Set<String> getSuperTypes(@NotNull String resourceType, @NotNull final ResourceResolver resourceResolver) {
```
Comment (jckautzmann) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/Utils.java:226]: I would prefer keeping the former implementation and not using the Java stream, which I find harder to debug and harder to follow with a recursion.

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ClientLibrariesImpl.java [hunk 2]
```diff
@@ -272,59 +282,62 @@ private String getInline(LibraryType libraryType) {
      *
      * @return {@link Set<String>} of clientlib categories
      */
+    @NotNull
     protected Set<String> getCategoriesFromComponents() {
-        Set<String> categories = new HashSet<>();
```
Comment (jckautzmann) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ClientLibrariesImpl.java:276]: Here also I would prefer keeping the former implementation and not using the Java stream, which I find harder to debug and harder to follow with a recursion.

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ClientLibrariesImpl.java [hunk 3]
```diff
@@ -272,59 +282,62 @@ private String getInline(LibraryType libraryType) {
...
-        if (StringUtils.equals(componentType, CQ_CLIENTLIBRARY_FOLDER)) {
-            ClientLibrary library = allLibraries.get(resource.getPath());
-            if (library != null) {
-                libraries.add(library);
-            }
-        }
-        for (Resource child : resource.getChildren()) {
-            addClientLibraries(child, libraries);
-        }
+    private static Stream<ClientLibrary> getClientLibraries(@org.jetbrains.annotations.Nullable final Resource resource,
```
Comment (jckautzmann) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ClientLibrariesImpl.java:323]: Here also I would prefer keeping the former implementation and not using the Java stream, which I find harder to debug and harder to follow with a recursion.

**Comment by jckautzmann** [comment]
Thx @ky940819 for your contribution! I tend to prefer this fix to the one suggested by @vladbailescu in #1120 because by completely removing the `Utils.getComponentsResolver` utility nobody won't be tempted to use it and forget about closing the resource resolver.

As stated in the PR, I would prefer keeping the former implementation and not using the Java stream, which I find harder to debug and harder to follow, especially when used with a recursion.

**Comment by ky940819** [comment]
@jckautzmann, I have updated the PR to remove the streams.
For future reference, do you not want the Java Stream API used at all in this project, or just recursive stream building?

Kyle

**Comment by jckautzmann** [comment]
thx @ky940819 for updating the PR.
I'm not a big fan of the Java Stream API: I have to admit that it's easy to read and write but harder to debug and sometimes understand (like when used with recursion).

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ClientLibrariesImpl.java [hunk 4]
```diff
@@ -272,59 +282,91 @@ private String getInline(LibraryType libraryType) {
...
-            for (String category : library.getCategories()) {
-                if (pattern != null) {
-                    if (pattern.matcher(category).matches()) {
-                        categories.add(category);
-                    }
-                } else {
-                    categories.add(category);
-                }
+    /**
+     * Get all resource types.
```
Comment (jckautzmann) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ClientLibrariesImpl.java:323]: I'd use the describing tense: Gets

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ClientLibrariesImpl.java [hunk 5]
```diff
@@ -272,59 +282,91 @@ private String getInline(LibraryType libraryType) {
...
-     * Adds client libraries to the provided collection, starting from the given resource
+     * Gets a list of client libraries, starting from the given resource
      * and diving into its descendants.
      *
      * @param resource - the given resource, which will be checked to see if it's a client library
-     * @param libraries - the provided collection of libraries to add to
+     * @param allLibraries - Map of all client libraries.
+     * @return List of client libraries for the given resource.
      */
-    private void addClientLibraries(Resource resource, Collection<ClientLibrary> libraries) {
```
Comment (vladbailescu) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ClientLibrariesImpl.java:314]: Same as above, we used `add*` to avoid creating new collection/set on each recursion.

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ComponentFilesImpl.java [hunk 6]
```diff
@@ -27,24 +28,33 @@
...
 public class ComponentFilesImpl implements ComponentFiles {
+    private static final Logger LOG = LoggerFactory.getLogger(ComponentFilesImpl.class);
 
-    @Self
-    SlingHttpServletRequest request;
+    /**
+     * Name of the subservice used to authenticate as in order to be able to read details about components and
+     * client libraries.
+     */
+    public static final String COMPONENTS_SERVICE = "components-service";
```
Comment (vladbailescu) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ComponentFilesImpl.java:57]: We could reuse previously defined constant.

Comment (ky940819) [reply bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ComponentFilesImpl.java:57]: We could.
The duplication was mostly an artifact of the refactoring.
However, I decided to leave it because the `ComponentFilesImpl.COMPONENTS_SERVICE` subservice and the `ClientLibrariesImpl.COMPONENTS_SERVICE` could potentially be different subservices and i didn't want to encourage a single catch-all subservice to be used across the entire project.

The constant probably should have been renamed. The clearest way might be to actually change the subservice names to something like "componentfiles-service" and "clientlibraries-service", and then provide two mappings to indicate these are different services, that just happen to have the same permissions.

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ClientLibrariesImpl.java (hunk 5 above)
Comment (ky940819) [reply bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ClientLibrariesImpl.java:314]: How about if we remove the recursion entirely. 
This re-introduces streams, but could be done without them. It just feels natural to me to use a stream for filtering a collection:

```JAVA
    @NotNull
    private static List<ClientLibrary> getClientLibraries(@org.jetbrains.annotations.Nullable final Resource resource,
                                                          @NotNull final Map<String, ClientLibrary> allLibraries) {
        return Optional.ofNullable(resource)
            .map(Resource::getPath)
            .map(path -> allLibraries.entrySet().stream()
                .filter(entry -> entry.getKey().equals(path) || entry.getKey().startsWith(path + "/"))
                .map(Map.Entry::getValue)
                .collect(Collectors.toList()))
            .orElseGet(Collections::emptyList);
    }
```

Since we never add a client library unless it exists in the `allLibraries` collection; why not just filter that collection?
I think that filtering an existing collection will perform better than even a small tree-traversal followed by a collection lookup. This also safe-guards against super expensive traversals that would result if there is a huge tree under the provided resource.

Comment (ky940819) [reply bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ClientLibrariesImpl.java:314]: As a side note, this is an example of where I personally enjoy streams.
A different style of coding, but the way I would write this would be to return the stream directly, and just `flatMap` it in '#getAllClientLibraries()', which would avoid the collection until the final results.

Comment (ky940819) [reply bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ClientLibrariesImpl.java:314]: Also, another thought.
Do we want to filter out clientlibs that don't allow proxy?
Since we are searching /apps or /libs for client libraries and then rendering them inline, we are effectively proxying them.

If we want to do that then it's just adding a
```JAVA
    .filter(ClientLibrary::allowProxy)
```

**Comment by ky940819** [comment]
@vladbailescu Do you have any thoughts on my responses? I'd love to get this cleared up. 
Thanks, kyle

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ClientLibrariesImpl.java (hunk 5 above)
Comment (vladbailescu) [reply bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ClientLibrariesImpl.java:314]: Filtering `allLibraries` might be actually better, you're right. I would not worry about `allowProxy` as embedding a non-proxied clientlib in a proxied one will also make it available, similarly to what we are doing.

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/Utils.java [hunk 7]
```diff
@@ -211,82 +203,33 @@ public static String generateId(String prefix, String path) {
...
      */
     @NotNull
-    public static Set<String> getSuperTypes(@NotNull String resourceType, @NotNull SlingHttpServletRequest request, ResourceResolverFactory resolverFactory) {
+    public static Set<String> getSuperTypes(@NotNull String resourceType, @NotNull final ResourceResolver resourceResolver) {
         Set<String> superTypes = new HashSet<>();
-        addSuperTypes(resourceType, superTypes, request, resolverFactory);
-        return superTypes;
-    }
-
-    private static void addSuperTypes(@NotNull String resourceType, @NotNull Set<String> superTypes, @NotNull SlingHttpServletRequest request, ResourceResolverFactory resolverFactory) {
```
[the remark this answers is not in the document]
Comment (vladbailescu) [reply bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/Utils.java:281]: Agree to just loop

**Comment by vladbailescu** [comment]
Hi Kyle, thanks for following through on this. I tried to answer to the open points, @jckautzmann will probably help you further as I'll be away for a (short) while.

**Review by vladbailescu — APPROVED** [review]
