### PR TITLE
[Image] Fix image broken when using on static template

### LINKED ISSUE #2095: [Image] Not able to set width and image quality on static template
## Bug Report

**Current Behavior**
1. Create a static template under /apps/xx/template
2. Create a proxy component to have resourceSuperType of "core/wcm/components/image/v2/image" or use we-retail image components. 
3. Add an image to image components and change width and image quality on design dialog.
4. Image fail to generate thought AdaptiveImageServlet.java5. 

**Expected behavior/code**
Expect to be getting design dialog valve if using static template

**Environment**
- AEM version and patch level AEM 6.5 SP9
- Core Components version 2.18.8
- JRE version Java(TM) SE Runtime Environment (build 1.8.0_202-b08)

**Possible Solution**

**Additional context / Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

### PR DESCRIPTION
**Pull request by leonso**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #2095  
| Patch: Bug Fix?          | Yes
| Minor: New Feature?      |
| Major: Breaking Change?  |
| Tests Added + Pass?      | Yes
| Documentation Provided   | Yes (code comments and or markdown)
| Any Dependency Changes?  |
| License                  | Apache License, Version 2.0

### CODE REVIEW

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java [hunk 1]
```diff
@@ -262,7 +263,7 @@ protected void doGet(@NotNull SlingHttpServletRequest request, @NotNull SlingHtt
                 metrics.markImageStreamed();
             }
         } catch (IllegalArgumentException e) {
-            LOGGER.error("Invalid image request", e.getMessage());
+            LOGGER.error("Invalid image request" + e.getMessage());
```
Comment (vladbailescu) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java:266]: It would be better to log the exception too: `LOGGER.error("Invalid image request", e)`

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java [hunk 2]
```diff
@@ -855,6 +856,17 @@ private ContentPolicy getContentPolicy(@NotNull Resource imageResource) {
         return null;
     }
 
+    /**
+     * Returns the designer bound to the given component.
+     *
+     * @param imageResource the resource identifying the accessed image component
+     * @return the designer. May be {@code null} in case no designer can be found.
+     */
+    private Designer getDesginer(@NotNull Resource imageResource) {
```
Comment (vladbailescu) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java:865]: Small typo: should be `getDesigner`

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java [hunk 3]
```diff
@@ -935,15 +947,23 @@ private ContentPolicy getContentPolicy(@NotNull Resource imageResource) {
     private List<Integer> getAllowedRenditionWidths(@NotNull Resource imageResource) {
         List<Integer> list = new ArrayList<>();
         ContentPolicy contentPolicy = getContentPolicy(imageResource);
+        Designer designer = getDesginer(imageResource);
```
Comment (vladbailescu) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java:950]: Since `adaptTo` is potentially expensive, I'd rather we call `getDesigner` in the `else` branch (when `contentPolicy` is null)

**Review by vladbailescu — CHANGES_REQUESTED** [review]
Thanks for your contribution. I requested a few small changes to be able to approve and merge the PR.
Could you also please contribute some tests?

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java [hunk 4]
```diff
@@ -262,7 +263,7 @@ protected void doGet(@NotNull SlingHttpServletRequest request, @NotNull SlingHtt
                 metrics.markImageStreamed();
             }
         } catch (IllegalArgumentException e) {
-            LOGGER.error("Invalid image request", e.getMessage());
+            LOGGER.error("Invalid image request" + e);
```
Comment (jckautzmann) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java:266]: I'd change to: `LOGGER.error("Invalid image request", e);`

Comment (leonso) [reply bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java:266]: Thanks for comment, should we change to `LOGGER.error("Invalid image request {}", e);` So the `e` can be log to log file

Comment (vladbailescu) [reply bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java:266]: @leonso , @jckautzmann has the same suggestion I had in https://github.com/adobe/aem-core-wcm-components/pull/2096#discussion_r829984889. https://logging.apache.org/log4j/2.x/log4j-api/apidocs/org/apache/logging/log4j/Logger.html#error-java.lang.CharSequence-java.lang.Throwable- will also log the stacktrace when passing the throwable as a second parameter.

**Comment by vladbailescu** [comment]
@leonso , added units tests via https://github.com/leonso/aem-core-wcm-components/pull/1

**Review by vladbailescu — APPROVED** [review]

**Comment by vladbailescu** [comment]
@leonso you still need to sign the Adobe Contributors License Agreement: http://opensource.adobe.com/cla.html
