### PR TITLE
GH-1936 - [Embed] XXE in OEmbedClientImpl.java

### LINKED ISSUE #1936: [Embed] XXE in OEmbedClientImpl.java
New H1 submission has been triaged and assigned to the adobe Team

Report ID: https://hackerone.com/reports/1438367
Program: adobe
Name: XXE in adobe/aem-core-wcm-components OEmbedClientImpl.java
CVSS Score: 7.5
CVSS Vector: CVSS:3.0/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:H/A:H
Date Received: 2021-12-30T22:59:30.823Z
**DISCLAIMER : Please reach out to PSIRT@adobe.com if this issue cannot be reproduced or additional information is required to remediate this vulnerability.**

| Details |
| --- |
| ```
Summary:
An authenticated user could reach OEmbedClientImpl.java to trigger an XXE vulnerability which enabled to read secret system files, DoS the system, perform SSRF, or aim at Remote Code Execution.

Platform(s) Affected:
Unknown

Steps To Reproduce:
Follow the source and sink trace from LGTM: https://lgtm.com/projects/g/adobe/aem-core-wcm-components/snapshot/00b370cf8202ee885b9c74abc60260d27fe6888b/files/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/services/embed/OEmbedClientImpl.java?sort=name&dir=ASC&mode=heatmap

Supporting Details:
Flow analysis from LGTM is pretty clear but a PoC could be provided if the asset is in scope. 

Supporting Material For Executable Assets:
https://lgtm.com/projects/g/adobe/aem-core-wcm-components/snapshot/00b370cf8202ee885b9c74abc60260d27fe6888b/files/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/services/embed/OEmbedClientImpl.java

Cheers.

  1. Impact

Read secret system files, DoS the system, perform SSRF or aim at Remote Code Execution.
``` |

### PR DESCRIPTION
**Pull request by jckautzmann**
- use a secured parser to parse the response before unmarshalling it

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #1936
| Patch: Bug Fix?          |
| Minor: New Feature?      |
| Major: Breaking Change?  |
| Tests Added + Pass?      | No
| Documentation Provided   | Yes (code comments and or markdown)
| Any Dependency Changes?  |
| License                  | Apache License, Version 2.0

### CODE REVIEW

**Review by bpauli — APPROVED** [review]

**Review by lkrapf — APPROVED** [review]
:+1:

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/services/embed/OEmbedClientImpl.java [hunk 1]
```diff
@@ -106,9 +111,19 @@ public OEmbedResponse getResponse(String url) {
...
+                InputStream xmlStream = getData(xmlURL);
+
+                //Disable XXE
+                SAXParserFactory spf = SAXParserFactory.newInstance();
+                spf.setFeature("http://xml.org/sax/features/external-general-entities", false);
+                spf.setFeature("http://xml.org/sax/features/external-parameter-entities", false);
+                spf.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false);
+
+                //Do unmarshall operation
+                Source xmlSource = new SAXSource(spf.newSAXParser().getXMLReader(), new InputSource(xmlStream));
```
Comment (kwin) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/services/embed/OEmbedClientImpl.java:123]: try..with..resources on both xmlreader and xmlstream as otherwise they might not be properly closed.

Comment (jckautzmann) [reply bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/services/embed/OEmbedClientImpl.java]: @kwin `spf.newSAXParser().getXMLReader()` is not a Closable, it cannot be used/closed with `try with resources`

Comment (kwin) [reply bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/services/embed/OEmbedClientImpl.java]: You are right, I have now seen it as well. Looks good now to me.
