### PR TITLE
GH-1807 - [Teaser v2] Get featured image from page linked in first CTA does not work

### LINKED ISSUE #1807: [Teaser v2] Get featured image from page linked in first CTA does not work.
* According to description on links tab, the teaser should pick the featured image from the first CTA link if that is set.

=> currently its not doing it , there is no error in console or error.log.

### PR DESCRIPTION
**Pull request by jckautzmann**
- support inheriting the page image from the call to action link: in the Sling model, in the adaptive image servlet and in the dialog thumbnail model
- add IT and Selenium tests to cover the main use cases of the image and the teaser components: inheriting the alt text and the featured image from either the current page, the linked page or the call to action link

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #1807, #1722
| Patch: Bug Fix?          |
| Minor: New Feature?      |
| Major: Breaking Change?  |
| Tests Added + Pass?      | Yes
| Documentation Provided   | 
| Any Dependency Changes?  |
| License                  | Apache License, Version 2.0

### CODE REVIEW

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/commons/editor/dialog/inherited/PageImageThumbnail.java [hunk 1]
```diff
@@ -95,36 +94,51 @@ protected void initModel() {
...
+            if (link != null) {
+                targetPage = (Page) link.getReference();
+            } else {
+                targetPage = currentPage;
+            }
         }
 
         if (targetPage == null) {
-            log.error("page is null");
+            log.info("The target page defined for {} is null", component.getPath());
```
Comment (richardhand) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/commons/editor/dialog/inherited/PageImageThumbnail.java:129]: @jckautzmann - this might not be `component.getPath()`, it could also be due to the `pageLinkParam` not pointing to a valid target page. Perhaps we should account for that in the log message?

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/Utils.java [hunk 2]
```diff
@@ -304,11 +303,15 @@ public static JSONObject getJsonOfRequestParameters(SlingHttpServletRequest requ
      * @param linkHandler The link handler
```
Comment (richardhand) [inline bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/Utils.java:303]: @jckautzmann - we should document the new style parameter

**Comment by richardhand** [comment]
@jckautzmann - there's a case I noticed when testing that seems not to work. If there are multiple action items, and each one links to a page that has a different featured image, then any change in the order of the items during a dialog session isn't reflected when switching to the Asset tab.

**To replicate:**
1. Ensure that there are some test pages available that each have a different featured image.
2. Open the dialog of a Teaser placed on a test page.
3. Add 2 or more actions, each linking to a different page from step 1.
4. Switch to the Asset tab, and notice how the image is the featured image of the first item.
5. Switch back to the Links tab and reorder the items.
6. Switch back to the Asset tab and notice how the image has not changed
Result -> The image hasn't been refreshed following reordereing.

File: bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v2/TeaserImplTest.java [hunk 3]
```diff
@@ -111,4 +112,36 @@ protected void testEmptyTeaserImageDelegatingToFeaturedImage() {
...
+    protected void testImageFromPage_withInvalidLink() {
+        Teaser teaser = getTeaserUnderTest(TEASER_22a);
+        Utils.testJSONExport(teaser, Utils.getTestExporterJSONPath(testBase, "teaser22a"));
+    }
+
+    @Test
+    protected void testImageFromPage_withCta() {
+        Teaser teaser = getTeaserUnderTest(TEASER_23);
+        Utils.testJSONExport(teaser, Utils.getTestExporterJSONPath(testBase, "teaser23"));
+    }
```
Comment (richardhand) [inline bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v2/TeaserImplTest.java:139]: @jckautzmann - would it be worth adding a case here with multiple CTA, to ensure it takes the first one?

**Comment by richardhand** [comment]
@jckautzmann - regarding https://github.com/adobe/aem-core-wcm-components/pull/1828#issuecomment-919938122, it seems to be a similar issue when deleting an item in the actions list.

File: testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/components/teaser/v1/Teaser.java [hunk 4]
```diff
@@ -32,6 +33,7 @@
     private static String teaserDescription = ".cmp-teaser__description";
     private static String teaserActionLink = "a.cmp-teaser__action-link";
     private static String imageTag = teaserImage + " img[src*='%s/_jcr_content/root/responsivegrid/teaser']";
+    public static String teaserWithAtlText = ".cmp-image__image[src*='%s/_jcr_content/root/responsivegrid/teaser.coreimg.'][alt='%s']";
```
Comment (richardhand) [inline testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/components/teaser/v1/Teaser.java:36]: `teaserWithAltText`

File: testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/components/teaser/v1/Teaser.java [hunk 5]
```diff
@@ -45,6 +47,14 @@ public boolean isImagePresent(String path) {
         return $(String.format(imageTag, path)).isDisplayed();
     }
 
+    public boolean isImagePresentWithFileName(String fileName) {
+        return $(String.format(imageWithFileName, fileName)).isDisplayed();
+    }
+
+    public boolean isImagePresentWithAtlText(String pagePath, String altText) {
```
Comment (richardhand) [inline testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/components/teaser/v1/Teaser.java:54]: `isImagePresentWithAltText`

**Comment by jckautzmann** [comment]
@richardhand The issue with updating the thumbnail when removing and reordering the CTAs has been addressed at https://github.com/adobe/aem-core-wcm-components/pull/1828/commits/803172ed81773a5d32fe1cba0cd612becac90eb5

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/commons/editor/dialog/inherited/PageImageThumbnail.java (hunk 1 above)
Comment (jckautzmann) [reply bundles/core/src/main/java/com/adobe/cq/wcm/core/components/commons/editor/dialog/inherited/PageImageThumbnail.java]: @richardhand Addressed in https://github.com/adobe/aem-core-wcm-components/pull/1828/commits/484eef1b066e43e55d44e6ffd343f556de31bccb

File: bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/Utils.java (hunk 2 above)
Comment (jckautzmann) [reply bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/Utils.java:303]: @richardhand Addressed in https://github.com/adobe/aem-core-wcm-components/pull/1828/commits/484eef1b066e43e55d44e6ffd343f556de31bccb

File: testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/components/teaser/v1/Teaser.java (hunk 4 above)
Comment (jckautzmann) [reply testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/components/teaser/v1/Teaser.java]: @richardhand Addressed in https://github.com/adobe/aem-core-wcm-components/pull/1828/commits/484eef1b066e43e55d44e6ffd343f556de31bccb

File: testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/components/teaser/v1/Teaser.java (hunk 5 above)
Comment (jckautzmann) [reply testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/components/teaser/v1/Teaser.java]: @richardhand Addressed in https://github.com/adobe/aem-core-wcm-components/pull/1828/commits/484eef1b066e43e55d44e6ffd343f556de31bccb

**Comment by richardhand** [comment]
@jckautzmann - re-tested with your latest changes and it seems to work well now.

File: bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v2/TeaserImplTest.java (hunk 3 above)
Comment (jckautzmann) [reply bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v2/TeaserImplTest.java:139]: @richardhand Addressed in https://github.com/adobe/aem-core-wcm-components/pull/1828/commits/2ed75881aa722610e982211bb46f1d9b7da9aaf7

**Review by richardhand — APPROVED** [review]

**Review by msagolj — APPROVED** [review]
