### PR TITLE
CC 2.18 Page V3 jQuery is not defined, _g is not define

### LINKED ISSUE #2040: CC 2.18 Page V3 jQuery is not defined, _g is not defined
## Bug Report

**Current Behavior**
When loading a Page V3, I assume due to the async clientlib integration, multiple javascript errors are being thrown on page refresh.

This can be reproduced by setting up a fresh 6.5.12 instance, installing the 2.18 Core Components and the Guides WKND pages.
Open a page, check the console, refresh the page and check the console again.

**Expected behavior/code**
The ootb code, without any customers / custom modification should not throw any javascript errors.

**Environment**
AEM 6.5.12
Core Components 2.18
Guides WKND 1.1.0

**Additional context / Screenshots**
image

Slight differences, depending on which core component is used / page composition. I do not have exact component setups on hand right now - sorry.

image

Ive found this Adobe Internal Slack link with the same issue: https://cq-dev.slack.com/archives/CR18QAQ75/p1646026384899809

### PR DESCRIPTION
**Pull request by bpauli**
- remove async attribute from script tag for shared libs
- append IT to verify result
#fixes 2040

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #2040 
| Patch: Bug Fix?          | 👍
| Minor: New Feature?      | 👎
| Major: Breaking Change?  |
| Tests Added + Pass?      | Yes
| Documentation Provided   | Yes (code comments and or markdown)
| Any Dependency Changes?  |
| License                  | Apache License, Version 2.0

### CODE REVIEW

**Review by jckautzmann — APPROVED** [review]

File: testing/it/http/src/test/java/com/adobe/cq/wcm/core/components/it/http/page/v3/PageIT.java [hunk 1]
```diff
@@ -52,4 +52,10 @@ public void testResponsiveGridStructure() throws ClientException {
         String content = adminAuthor.doGet("/content/core-components/simple-page/simple-page-v3.html", 200).getContent();
         GraniteAssert.assertRegExFind(content, "Basic Title");
     }
+
+    @Test
+    public void testHeadJSLibs() throws ClientException {
+        String content = adminAuthor.doGet("/content/core-components/simple-page/simple-page-v3.html", 200).getContent();
+        GraniteAssert.assertRegExFind(content, "<script src=\"/etc.clientlibs/foundation/clientlibs/jquery.js\"></script>");
```
Comment (vladbailescu) [inline testing/it/http/src/test/java/com/adobe/cq/wcm/core/components/it/http/page/v3/PageIT.java:59]: This pattern will most probably not work with the long-term caching suffixes (see https://github.com/adobe/aem-core-wcm-components/blob/main/testing/it/http/src/test/java/com/adobe/cq/wcm/core/components/it/http/ClientlibsIncludeIT.java#L44 for a possible solution)
