### PR TITLE
[Accessibility][Teaser][Dialog] Visible label/form field are not associated

### LINKED ISSUE #1921: [Accessibility][Teaser][Dialog] Visible label/form field are not associated
##### **Environment**
Testing Application - Adobe Experience Manager
Authentication State -  Logged in
URL - https://author-p35316-e137331.adobeaemcloud.com/sites.html/content
Operating System - Windows 10
Browser - Chrome Version 93.0
Assistive Technology - NVDA Version 2021.2
Context - Desktop

##### **Steps to Reproduce**
1. Launch the 'Adobe Experience Manager' application.
2. Sign in with the Email and Password (registered email).
3. 'AEM Start' page will appear.
4. Activate the 'Sites' link.
5. 'AEM Sites' page will appear.
6. Select the 'WKND Site' option.
7. WKND Site | AEM Sites page will appear.
8. Select the United States option.
9. United States | AEM Sites page will appear.
10. Select the  'WKND Adventures and Travel' option.
11. WKND Adventures and Travel | AEM Sites page will appear.
12. Select the 'Magazine' option and activate the 'Edit button.
13. 'Magazine' page will appear.
14. Scroll to the bottom of the page and click on the 'Teaser' component.
15. Select the 'Configure' option in the toolbar.
16. 'Teaser' modal will appear.
17. Select the 'Text' tab and observe the 'Description' field.

##### **Expected Results** 
The visible label- "Description" is also announced by the screen reader along with the "multi-line editable field" 
 
##### **Actual Results** 
The visible label- "Description" is not announced by the screen reader along with the "multi-line editable field"

##### **Affected user population**
Without Vision, With Limited Vision

##### **Applicable WCAG SC**
1.3.1 Info and Relationships (Level A)

##### **Source Code**
<label id="label_10a41154-9af8-480b-9413-183a300a852f" class="coral-Form-fieldlabel">Description</label>

##### **Remediation recommendation**
Fix this issue by using ONE of the following techniques:
1. Explicit label: Under most circumstances, the best technique is to use the <label> element with the for attribute. The value of the for attribute is the id attribute value of the <input> element.

<label for="fname">First Name:</label> 
<input type="text" name="fn" id="fname">

2. Use an aria-label attribute or title attribute on the <input> to provide a label when there is no visible label.

<input type="text" aria-label="search"> <input type="submit" value="Search">

3. Use an aria-labelledby attribute on the <input> to reference a visible label. The value of the aria-labelledby attribute is the id attribute value of the visible text label.

<span id="nickname">Nickname:</span> <input type="text" aria-labelledby="nickname">

4. Implicit label (explicit label method is strongly preferred): Wrap the form element within the <label> element.

<label>First Name: <input type="text" name="fn"></label>

REFERENCE: 
Deque University: https://dequeuniversity.com/class/forms2/labels/semantic-labels
W3C-WAI tutorial: https://www.w3.org/WAI/tutorials/forms/

### PR DESCRIPTION
**Pull request by comanV**
Fixes #1921.

### CODE REVIEW

File: content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/clientlibs/editor/js/teaser.js [hunk 1]
```diff
@@ -198,4 +199,11 @@
             }
         }
     }
+
+    function associateDescriptionTextFieldWithLabel(descriptionTextfieldElement) {
+        var richTextContainerSelector = ".cq-RichText.richtext-container";
+        var $richTextContainerParent = $(richTextContainerSelector)[0].parentNode;
+        var $descriptionLabel = $richTextContainerParent.children[0];
```
Comment (vladbailescu) [inline content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/clientlibs/editor/js/teaser.js:206]: I think this is error-prone as:
- there's no check the elements actually exist
- `.children[0]` might not be the right element if the RTE structure changes

File: content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/clientlibs/editor/js/teaser.js [hunk 2]
```diff
@@ -198,4 +199,11 @@
             }
         }
     }
+
+    function associateDescriptionTextFieldWithLabel(descriptionTextfieldElement) {
+        var richTextContainerSelector = ".cq-RichText.richtext-container";
```
Comment (vladbailescu) [inline content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/clientlibs/editor/js/teaser.js:204]: Ideally the issue should be fixed in the RTE. We should only add an `arria-labelledby` as a fallback/workaround, if the RTE does not provide one.

**Review by vladbailescu — CHANGES_REQUESTED** [review]

File: content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/clientlibs/editor/js/teaser.js (hunk 2 above)
Comment (comanV) [reply content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/clientlibs/editor/js/teaser.js]: Addressed in c35eb464660b246a05ee2955a6f9c8b179a98d09.
